name: sm_model
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - tensorflow=2.5.0
    - earthengine-api
    - pip
    - pip:
        - pyyaml
        - ismn
