### Directories ###
project_name                    : rnn_sm_model
wrk_dir                         : \path\to\working_directory
data_dir                        : \path\to\data # for ICOS this will be the main folder and for ISMN it is the .zip

### Preprocessing specifications ###
variables                       : ['TS', 'TA', 'P', 'VV', 'VH', 'NDVI', 'NDWI'] # soil temperature, air temperature, precipitation, vertical-vertical (SAR), vertical-horizontal (SAR), Normalized difference vegetation index, Normalized difference (vegetation) water index
overwrite_variables             : false
interpolate_index               : true
data_source                     : ISMN
network_name                    : REMEDHUS # only used for ISMN probes
swc_depth_range                 : [0.0, 0.05] # only used for ISMN probes
do_plot                         : true
smooth_plot                     : true
